package movieTicketBookingInterfaceApp;


/**
* movieTicketBookingInterfaceApp/movieTicketBookingInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from movieTicketBookingInterface.idl
* Friday, 24 February, 2023 7:05:33 PM EST
*/

public interface movieTicketBookingInterface extends movieTicketBookingInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface movieTicketBookingInterface
