package movieTicketBookingInterfaceApp;


/**
* movieTicketBookingInterfaceApp/movieTicketBookingInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from movieTicketBookingInterface.idl
* Friday, 24 February, 2023 7:05:33 PM EST
*/

abstract public class movieTicketBookingInterfaceHelper
{
  private static String  _id = "IDL:movieTicketBookingInterfaceApp/movieTicketBookingInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, movieTicketBookingInterfaceApp.movieTicketBookingInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static movieTicketBookingInterfaceApp.movieTicketBookingInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (movieTicketBookingInterfaceApp.movieTicketBookingInterfaceHelper.id (), "movieTicketBookingInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static movieTicketBookingInterfaceApp.movieTicketBookingInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_movieTicketBookingInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, movieTicketBookingInterfaceApp.movieTicketBookingInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static movieTicketBookingInterfaceApp.movieTicketBookingInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof movieTicketBookingInterfaceApp.movieTicketBookingInterface)
      return (movieTicketBookingInterfaceApp.movieTicketBookingInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      movieTicketBookingInterfaceApp._movieTicketBookingInterfaceStub stub = new movieTicketBookingInterfaceApp._movieTicketBookingInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static movieTicketBookingInterfaceApp.movieTicketBookingInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof movieTicketBookingInterfaceApp.movieTicketBookingInterface)
      return (movieTicketBookingInterfaceApp.movieTicketBookingInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      movieTicketBookingInterfaceApp._movieTicketBookingInterfaceStub stub = new movieTicketBookingInterfaceApp._movieTicketBookingInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
