package movieTicketBookingInterfaceApp;

/**
* movieTicketBookingInterfaceApp/movieTicketBookingInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from movieTicketBookingInterface.idl
* Friday, 24 February, 2023 7:05:33 PM EST
*/

public final class movieTicketBookingInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public movieTicketBookingInterfaceApp.movieTicketBookingInterface value = null;

  public movieTicketBookingInterfaceHolder ()
  {
  }

  public movieTicketBookingInterfaceHolder (movieTicketBookingInterfaceApp.movieTicketBookingInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = movieTicketBookingInterfaceApp.movieTicketBookingInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    movieTicketBookingInterfaceApp.movieTicketBookingInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return movieTicketBookingInterfaceApp.movieTicketBookingInterfaceHelper.type ();
  }

}
